apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-profile
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: simple-profile.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: simple-profile
            port:
              number: 80
