apiVersion: v1
kind: Service
metadata:
  name: simple-profile
  labels:
    app: simple-profile
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: simple-profile
  type: ClusterIP